Several updates to site generation
 - Update site plugin to remove NoSuchMethodError
 - Use Maven Fluido Skin, the only skin mainained by the Maven project.
 - Replace various links with HTTPS